# Generated by Django 2.1.2 on 2018-10-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('IdCiudad', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Rut', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('FechaNaci', models.DateField()),
                ('Telefono', models.IntegerField()),
                ('Vivienda', models.CharField(max_length=45)),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Correo', models.EmailField(max_length=45, primary_key=True, serialize=False)),
                ('Pass', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('IdRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Login'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
