# Generated by Django 2.1.2 on 2018-10-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181028_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Correo',
            new_name='Usuario',
        ),
    ]
