# Generated by Django 2.1.2 on 2018-10-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
