# Generated by Django 2.1.2 on 2018-10-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Pass', models.CharField(max_length=45)),
                ('TipoAdmin', models.CharField(max_length=45)),
            ],
        ),
    ]
