# Generated by Django 2.1.2 on 2018-10-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='TipoAdmin',
            new_name='TipoUsuario',
        ),
    ]
