# Generated by Django 2.1.2 on 2018-10-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181029_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Usuario',
            new_name='Correo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Correo',
            field=models.EmailField(max_length=45),
        ),
    ]
