# Generated by Django 2.1.2 on 2018-10-31 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181030_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascotas',
            new_name='Mascota',
        ),
    ]
