# Generated by Django 2.1.2 on 2018-10-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181030_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Contacto',
        ),
    ]
