# Generated by Django 2.1.2 on 2018-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181030_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='IdMascotas',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='Nombre',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
