# Generated by Django 2.1.2 on 2018-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181030_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='Foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
