# Generated by Django 2.1.2 on 2018-11-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20181031_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='IdCiudad',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='IdRegion',
            new_name='Region',
        ),
    ]
