# Generated by Django 2.1.2 on 2018-11-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181101_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nueva',
            fields=[
                ('Rut', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Correo', models.EmailField(max_length=45)),
                ('FechaNaci', models.DateField()),
                ('Telefono', models.IntegerField()),
                ('Vivienda', models.CharField(max_length=45)),
                ('Region', models.CharField(max_length=45)),
                ('Ciudad', models.CharField(max_length=45)),
            ],
        ),
    ]
