# Generated by Django 2.1.2 on 2018-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_nueva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nueva',
            name='Ciudad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nueva',
            name='Region',
            field=models.IntegerField(),
        ),
    ]
