# Generated by Django 2.1.2 on 2018-11-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20181101_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nueva',
            name='Ciudad',
        ),
        migrations.RemoveField(
            model_name='nueva',
            name='Region',
        ),
        migrations.DeleteModel(
            name='Nueva',
        ),
    ]
