# Generated by Django 2.1.2 on 2018-11-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20181101_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='Ciudad',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='Region',
        ),
    ]
