# Generated by Django 2.1.2 on 2018-11-01 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_nueva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nueva',
        ),
    ]
