# Generated by Django 2.1.2 on 2018-11-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_nueva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
