# Generated by Django 2.1.2 on 2018-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAdopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Telefono', models.IntegerField()),
                ('Mensaje', models.TextField(max_length=250)),
            ],
        ),
    ]
