# Generated by Django 2.1.2 on 2018-11-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_contactoadopt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
